
const K={ scopeMode:'unote.scopeMode', settings:'unote.settings', panelVisible:'unote.panelVisible', pluginEnabled:'unote.pluginEnabled', showMarkerLabels:'unote.showMarkerLabels' };
const NOTE_PREFIX='unote.note:';
const DEFAULT_SETTINGS={ singleHotkey:{key:'`',code:'Backquote',ctrl:false,alt:false,shift:false,meta:false,enabled:true}, rangeHotkey:{key:'`',code:'Backquote',ctrl:true,alt:false,shift:false,meta:false,enabled:true} };
const ICONS={ time:'<svg viewBox="0 0 24 24"><path d="M12 7v5l3 3"/><circle cx="12" cy="12" r="8"/></svg>', range:'<svg viewBox="0 0 24 24"><path d="M4 7h8"/><path d="M12 17h8"/><path d="M10 7l2-2 2 2"/><path d="M14 17l-2 2-2-2"/></svg>', note:'<svg viewBox="0 0 24 24"><path d="M7 4h10a2 2 0 0 1 2 2v12l-4-2-4 2-4-2-4 2V6a2 2 0 0 1 2-2z"/></svg>', save:'<svg viewBox="0 0 24 24"><path d="M6 4h9l3 3v13H6z"/><path d="M9 4v5h6"/><path d="M9 18h6"/></svg>', clear:'<svg viewBox="0 0 24 24"><path d="M6 7h12"/><path d="M9 7V5h6v2"/><path d="M8 7l1 12h6l1-12"/><path d="M10 10v6"/><path d="M14 10v6"/></svg>', settings:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.5-2.3 1a7 7 0 0 0-1.7-1L14.5 3h-5L9 6a7 7 0 0 0-1.7 1L5 6 3 9.5 5 11a7 7 0 0 0 0 2l-2 1.5L5 18l2.3-1a7 7 0 0 0 1.7 1l.5 3h5l.5-3a7 7 0 0 0 1.7-1L19 18l2-3.5-2-1.5c.1-.3.1-.7.1-1z"/></svg>', source_active:'<svg viewBox="0 0 24 24"><path d="M12 3v18"/><path d="M5 10l7-7 7 7"/></svg>', source_manual:'<svg viewBox="0 0 24 24"><path d="M6 5h12"/><path d="M6 12h12"/><path d="M6 19h12"/></svg>', lock:'<svg viewBox="0 0 24 24"><rect x="6" y="11" width="12" height="9" rx="2"/><path d="M9 11V8a3 3 0 1 1 6 0v3"/></svg>', unlock:'<svg viewBox="0 0 24 24"><rect x="6" y="11" width="12" height="9" rx="2"/><path d="M15 11V8a3 3 0 0 0-6 0"/></svg>', power_on:'<svg viewBox="0 0 24 24"><path d="M12 3v8"/><path d="M7 5.5a7 7 0 1 0 10 0"/></svg>', power_off:'<svg viewBox="0 0 24 24"><path d="M12 3v8"/><path d="M7 5.5a7 7 0 0 0 10 10"/><path d="M4 4l16 16"/></svg>', eye_on:'<svg viewBox="0 0 24 24"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12z"/><circle cx="12" cy="12" r="3"/></svg>', eye_off:'<svg viewBox="0 0 24 24"><path d="M4 4l16 16"/><path d="M10.6 10.6a2 2 0 0 0 2.8 2.8"/><path d="M9.2 5.5A11.6 11.6 0 0 1 12 6c6.5 0 10 6 10 6a16.8 16.8 0 0 1-4.2 4.6"/><path d="M6.2 6.4A17.2 17.2 0 0 0 2 12s3.5 6 10 6a11.8 11.8 0 0 0 4-.7"/></svg>' };
const noteEl=document.getElementById('note'), contextKindEl=document.getElementById('contextKind'), contextLabelEl=document.getElementById('contextLabel'), pendingHintEl=document.getElementById('pendingHint'), statusEl=document.getElementById('status'), settingsBox=document.getElementById('settingsBox'), singleHotkeyDisplay=document.getElementById('singleHotkeyDisplay'), rangeHotkeyDisplay=document.getElementById('rangeHotkeyDisplay');
let captureMode=null,currentContext=null,saveTimer=null,pluginEnabled=true,showMarkerLabels=true,sourceState={source:null,locked:false,tabs:[]},lastLocalNoteWriteAt=0,lastNoteSelectionStart=0,lastNoteSelectionEnd=0,suppressLiteralUntil=0;
const get=(k)=>new Promise(r=>chrome.storage.local.get(k,r)), set=(o)=>new Promise(r=>chrome.storage.local.set(o,r));
const runtimeSend=(message)=>new Promise((resolve)=>{ chrome.runtime.sendMessage(message,response=>{ if(chrome.runtime.lastError) return resolve({ success:false, error:chrome.runtime.lastError.message||'Lỗi kết nối extension.' }); resolve(response||{ success:false, error:'Không nhận được phản hồi.' }); }); });
const tabSend=(tabId,message)=>new Promise((resolve)=>{ chrome.tabs.sendMessage(tabId,message,response=>{ if(chrome.runtime.lastError) return resolve({ success:false, error:chrome.runtime.lastError.message||'Không gửi được message sang tab hiện tại.' }); resolve(response||{ success:false, error:'Tab hiện tại không phản hồi.' }); }); });
function setStatus(msg,type=''){ statusEl.textContent=msg; statusEl.className=type; }
function formatHotkey(hk){ if(!hk||hk.enabled===false) return 'Tắt'; const p=[]; if(hk.ctrl)p.push('Ctrl'); if(hk.alt)p.push('Alt'); if(hk.shift)p.push('Shift'); if(hk.meta)p.push('Meta'); let keyLabel=hk.key||hk.code||''; if(hk.code==='Backquote') keyLabel='`'; p.push(keyLabel||hk.code||''); return p.join(' + '); }
function isModifierOnlyEvent(e){ return ['Control','Shift','Alt','Meta'].includes(e.key); }
function isBackquoteHotkey(hk){ return hk && (hk.code==='Backquote' || hk.key==='`'); }
function eventMatchesHotkey(e,hk){ if(!hk||hk.enabled===false) return false; const codeMatch=hk.code?e.code===hk.code:true; const keyMatch=hk.key?String(e.key).toLowerCase()===String(hk.key).toLowerCase():true; return codeMatch&&keyMatch&&!!e.ctrlKey===!!hk.ctrl&&!!e.altKey===!!hk.alt&&!!e.shiftKey===!!hk.shift&&!!e.metaKey===!!hk.meta; }
function rememberNoteSelection(){ try{ lastNoteSelectionStart=noteEl.selectionStart||0; lastNoteSelectionEnd=noteEl.selectionEnd||0; }catch(e){} }
function applyNoteValue(newValue,preserveCaret=true){ const next=String(newValue||''); if(noteEl.value===next) return; const active=document.activeElement===noteEl; const start=active?(noteEl.selectionStart||0):lastNoteSelectionStart; const end=active?(noteEl.selectionEnd||0):lastNoteSelectionEnd; const scrollTop=noteEl.scrollTop; noteEl.value=next; if(active&&preserveCaret){ const max=noteEl.value.length; noteEl.focus(); noteEl.setSelectionRange(Math.min(start,max),Math.min(end,max)); noteEl.scrollTop=scrollTop; rememberNoteSelection(); } }
function makeIconButton(id,title,iconKey,extraClass=''){ const button=document.createElement('button'); button.id=id; button.className=`icon-btn ${extraClass}`.trim(); button.type='button'; button.title=title; button.setAttribute('aria-label',title); button.innerHTML=ICONS[iconKey]||''; return button; }
function setButtonIcon(btn,key,title){ btn.innerHTML=ICONS[key]||''; btn.title=title; btn.setAttribute('aria-label',title); }
function ensureActionIcons(){ const actions=document.querySelector('.actions'); if(actions.dataset.ready==='1') return; actions.innerHTML=''; actions.appendChild(makeIconButton('btnSingle','Quick Note mốc đơn','time')); actions.appendChild(makeIconButton('btnRange','Quick Note đầu/cuối','range')); actions.appendChild(makeIconButton('btnFree','Quick Note free','note')); actions.appendChild(makeIconButton('btnToggleLabels','Bật/tắt text marker','eye_on')); actions.appendChild(makeIconButton('btnSave','Lưu note','save')); actions.appendChild(makeIconButton('btnClear','Xóa note','clear')); actions.appendChild(makeIconButton('btnSettings','Mở settings','settings')); actions.appendChild(makeIconButton('btnSourceActive','Chọn tab hiện tại làm nguồn','source_active')); actions.appendChild(makeIconButton('btnSourceManual','Đổi source thủ công','source_manual')); actions.appendChild(makeIconButton('btnSourceLock','Khóa tab nguồn','lock')); actions.appendChild(makeIconButton('btnPluginToggle','Tắt plugin','power_on','power-btn')); actions.dataset.ready='1'; }
function updatePluginUI(){ const disabled=!pluginEnabled; noteEl.disabled=disabled; document.querySelectorAll('#btnSingle,#btnRange,#btnFree,#btnToggleLabels,#btnSave,#btnClear,#btnSourceActive,#btnSourceManual,#btnSourceLock,#btnSettings,.scope-btn').forEach(el=>{ if(el) el.disabled=disabled; }); const powerBtn=document.getElementById('btnPluginToggle'); if(powerBtn) setButtonIcon(powerBtn,pluginEnabled?'power_on':'power_off',pluginEnabled?'Tắt plugin':'Mở plugin'); const labelsBtn=document.getElementById('btnToggleLabels'); if(labelsBtn) setButtonIcon(labelsBtn,showMarkerLabels?'eye_on':'eye_off',showMarkerLabels?'Đang bật text marker':'Đang tắt text marker'); }
function renderSourceState(){ const source=sourceState.source; const parts=[]; parts.push(source?`Nguồn: #${source.id}`:'Nguồn: chưa chọn'); if(source?.title) parts.push(source.title); parts.push(sourceState.locked?'🔒 Locked':'🔓 Auto'); parts.push(pluginEnabled?'✅ On':'⛔ Off'); parts.push(showMarkerLabels?'📝 Text On':'🙈 Text Off'); contextLabelEl.textContent=parts.join(' • '); const lockBtn=document.getElementById('btnSourceLock'); if(lockBtn) setButtonIcon(lockBtn,sourceState.locked?'lock':'unlock',sourceState.locked?'Mở khóa tab nguồn':'Khóa tab nguồn'); }
async function getSettings(){ const d=await get([K.settings]); const s=d[K.settings]||{}; return { singleHotkey:{...DEFAULT_SETTINGS.singleHotkey,...(s.singleHotkey||{})}, rangeHotkey:{...DEFAULT_SETTINGS.rangeHotkey,...(s.rangeHotkey||{})} }; }
async function saveSettings(settings){ await set({[K.settings]:settings}); }
async function renderSettings(){ const s=await getSettings(); singleHotkeyDisplay.value=formatHotkey(s.singleHotkey); rangeHotkeyDisplay.value=formatHotkey(s.rangeHotkey); }
async function getScopeMode(){ const d=await get([K.scopeMode]); return d[K.scopeMode]||'global'; }
async function setScopeMode(mode){ await set({[K.scopeMode]:mode}); }
async function loadShowLabels(){ const d=await get([K.showMarkerLabels]); showMarkerLabels = d[K.showMarkerLabels] !== false; }
async function setShowLabels(value){ showMarkerLabels = !!value; await set({ [K.showMarkerLabels]: showMarkerLabels }); updatePluginUI(); renderSourceState(); }
async function getPageState(){ const tabs=await chrome.tabs.query({active:true,currentWindow:true}); const tab=tabs[0]; const url=tab?.url||''; const pageResp=await tabSend(tab.id,{type:'UNOTE_GET_CONTEXT'}); const scopeMode=await getScopeMode(); const parsed=url?new URL(url):{origin:'unknown',pathname:'unknown'}; const pageKey=`${parsed.origin}${parsed.pathname}`; const ctx = scopeMode==='global' ? {key:`${NOTE_PREFIX}global`,sourceType:'global',sourceLabel:'global',scopeMode,speechMiner:!!pageResp?.context?.speechMiner,externalId:''} : scopeMode==='externalId' && pageResp?.context?.speechMiner && pageResp?.context?.externalId ? {key:`${NOTE_PREFIX}externalId:${pageResp.context.externalId}`,sourceType:'externalId',sourceLabel:`externalId: ${pageResp.context.externalId}`,scopeMode,speechMiner:true,externalId:pageResp.context.externalId} : scopeMode==='externalId' ? {key:`${NOTE_PREFIX}page:${pageKey}`,sourceType:'page-fallback',sourceLabel:`page (fallback): ${pageKey}`,scopeMode,speechMiner:!!pageResp?.context?.speechMiner,externalId:''} : {key:`${NOTE_PREFIX}page:${pageKey}`,sourceType:'page',sourceLabel:`page: ${pageKey}`,scopeMode:'page',speechMiner:!!pageResp?.context?.speechMiner,externalId:pageResp?.context?.externalId||''}; return {tab,url,ctx}; }
async function refreshSourceState(showStatus=false){ const state=await runtimeSend({type:'UNOTE_GET_SOURCE_STATE'}); if(state.success===false){ setStatus(state.error||'Không đọc được source state','err'); return; } sourceState={source:state.source||null,locked:!!state.locked,tabs:state.tabs||[]}; pluginEnabled=state.pluginEnabled!==false; renderSourceState(); updatePluginUI(); if(showStatus) setStatus(sourceState.source?`Đã cập nhật source #${sourceState.source.id}`:'Chưa có source tab','ok'); }
async function loadCurrentNote(forceStatus=true){ const state=await getPageState(); currentContext=state.ctx; const d=await get([currentContext.key,K.pluginEnabled]); pluginEnabled=d[K.pluginEnabled]!==false; applyNoteValue(d[currentContext.key]||'',true); contextKindEl.textContent=currentContext.speechMiner?'SpeechMiner':'General'; contextKindEl.style.background=currentContext.speechMiner?'#dbeafe':'#e5e7eb'; contextKindEl.style.color=currentContext.speechMiner?'#1d4ed8':'#374151'; document.getElementById('scopeGlobal').classList.toggle('active',currentContext.scopeMode==='global'); document.getElementById('scopePage').classList.toggle('active',currentContext.scopeMode==='page'); document.getElementById('scopeExternal').classList.toggle('active',currentContext.scopeMode==='externalId'); document.getElementById('scopeExternal').disabled=!pluginEnabled||!(currentContext.speechMiner&&currentContext.externalId); pendingHintEl.textContent=''; await loadShowLabels(); await refreshSourceState(false); currentContext = state.ctx; if(forceStatus) setStatus(currentContext.sourceType==='global'?'Đã tải note global':currentContext.sourceType==='externalId'?'Đã tải note theo externalId':'Đã tải note theo page','ok'); }
async function saveCurrentNote(showStatus=true,markLocal=true){ if(!currentContext) await loadCurrentNote(false); if(markLocal) lastLocalNoteWriteAt=Date.now(); await set({[currentContext.key]:noteEl.value}); if(showStatus) setStatus('Đã lưu vào chrome.storage.local','ok'); }
async function clearCurrentNote(){ if(!currentContext) await loadCurrentNote(false); lastLocalNoteWriteAt=Date.now(); await set({[currentContext.key]:''}); applyNoteValue('',false); setStatus('Đã xóa note','ok'); }
async function chooseSourceManual(){ await refreshSourceState(false); if(!sourceState.tabs.length) return setStatus('Không có tab SpeechMiner nào đang mở.','err'); const options=sourceState.tabs.map(tab=>`#${tab.id} - ${tab.title}`).join('\n'); const current=sourceState.source?.id?String(sourceState.source.id):''; const input=window.prompt(`Nhập ID tab SpeechMiner muốn chọn làm nguồn:\n\n${options}`,current); if(input===null) return; const tabId=Number(input.trim()); if(!Number.isFinite(tabId)) return setStatus('ID tab không hợp lệ.','err'); const r=await runtimeSend({type:'UNOTE_SET_SOURCE_MANUAL',tabId}); if(!r?.success) return setStatus(r?.error||'Không đổi được source.','err'); await refreshSourceState(true); }
async function setActiveTabAsSource(){ const r=await runtimeSend({type:'UNOTE_SET_SOURCE_ACTIVE_TAB'}); if(!r?.success) return setStatus(r?.error||'Không chọn được tab nguồn.','err'); await refreshSourceState(true); }
async function toggleSourceLock(){ const r=await runtimeSend({type:'UNOTE_SET_SOURCE_LOCKED',locked:!sourceState.locked}); if(!r?.success) return setStatus(r?.error||'Không đổi được trạng thái lock.','err'); sourceState.locked=!!r.locked; renderSourceState(); setStatus(sourceState.locked?'Đã khóa tab nguồn':'Đã mở khóa tab nguồn','ok'); }
async function togglePlugin(){ const r=await runtimeSend({type:'UNOTE_TOGGLE_PLUGIN'}); if(!r?.success) return setStatus(r?.error||'Không đổi được trạng thái plugin.','err'); pluginEnabled=!!r.pluginEnabled; await set({[K.pluginEnabled]:pluginEnabled}); renderSourceState(); updatePluginUI(); setStatus(pluginEnabled?'Đã mở plugin':'Đã tắt plugin',pluginEnabled?'ok':'warn'); }
async function openQuickNote(mode){ const r=await runtimeSend({type:'UNOTE_OPEN_INLINE_QUICKNOTE', mode}); if(!r?.success) return setStatus(r?.error||'Không mở được Quick Note.','err'); setStatus('Đã mở Quick Note trên trang hiện tại','ok'); }
async function captureHotkey(e){ if(!captureMode) return false; if(isModifierOnlyEvent(e)) return true; e.preventDefault(); e.stopPropagation(); const s=await getSettings(); const hk={key:e.key,code:e.code,ctrl:!!e.ctrlKey,alt:!!e.altKey,shift:!!e.shiftKey,meta:!!e.metaKey,enabled:true}; if(captureMode==='single') s.singleHotkey=hk; if(captureMode==='range') s.rangeHotkey=hk; await saveSettings(s); captureMode=null; await renderSettings(); setStatus('Đã lưu hotkey mới','ok'); return true; }
async function handleSidePanelHotkeys(e){ if(captureMode){ const consumed=await captureHotkey(e); if(consumed) return true; } if(!pluginEnabled) return false; const active=document.activeElement; if(active&&active.tagName==='SELECT') return false; const s=await getSettings(); if(eventMatchesHotkey(e,s.singleHotkey)){ if(isBackquoteHotkey(s.singleHotkey)) suppressLiteralUntil=Date.now()+800; e.preventDefault(); e.stopImmediatePropagation(); e.stopPropagation(); await openQuickNote('single'); return true; } if(eventMatchesHotkey(e,s.rangeHotkey)){ if(isBackquoteHotkey(s.rangeHotkey)) suppressLiteralUntil=Date.now()+800; e.preventDefault(); e.stopImmediatePropagation(); e.stopPropagation(); await openQuickNote('range'); return true; } return false; }
chrome.runtime.onMessage.addListener((message)=>{ if(message?.type==='UNOTE_NOTE_APPENDED'){ if(currentContext?.key && message.contextKey===currentContext.key){ const active=document.activeElement===noteEl; const start=active?(noteEl.selectionStart||0):lastNoteSelectionStart; const end=active?(noteEl.selectionEnd||0):lastNoteSelectionEnd; const scrollTop=noteEl.scrollTop; noteEl.value = message.nextValue || noteEl.value; if(active){ const max=noteEl.value.length; noteEl.focus(); noteEl.setSelectionRange(Math.min(start,max),Math.min(end,max)); noteEl.scrollTop=scrollTop; rememberNoteSelection(); } setStatus('Đã đồng bộ note chính ngay sau khi add','ok'); } } });
chrome.storage.onChanged.addListener(async(changes,area)=>{ if(area!=='local') return; if(changes[K.settings]) await renderSettings(); if(changes[K.pluginEnabled]){ pluginEnabled=changes[K.pluginEnabled].newValue!==false; renderSourceState(); updatePluginUI(); } if(changes[K.showMarkerLabels]){ showMarkerLabels = changes[K.showMarkerLabels].newValue !== false; renderSourceState(); updatePluginUI(); } if(changes[K.scopeMode]){ await loadCurrentNote(false); return; } if(currentContext&&changes[currentContext.key]){ const newValue=changes[currentContext.key].newValue||''; const isLocalEcho=(Date.now()-lastLocalNoteWriteAt<1200)&&newValue===noteEl.value; if(isLocalEcho) return; if(document.activeElement===noteEl && newValue===noteEl.value) return; applyNoteValue(newValue,true); } });
document.addEventListener('keydown',e=>{ handleSidePanelHotkeys(e).catch(console.error); },true);
noteEl.addEventListener('beforeinput',e=>{ if(Date.now()<suppressLiteralUntil&&e.data==='`') e.preventDefault(); });
noteEl.addEventListener('input',()=>{ rememberNoteSelection(); clearTimeout(saveTimer); saveTimer=setTimeout(()=>saveCurrentNote(false,true).catch(console.error),600); });
['click','keyup','select','focus','blur','mouseup'].forEach(evt=>noteEl.addEventListener(evt,rememberNoteSelection));
window.addEventListener('focus',()=>loadCurrentNote(false).catch(console.error));
window.addEventListener('beforeunload',()=>chrome.storage.local.set({[K.panelVisible]:false}));
document.addEventListener('visibilitychange',()=>chrome.storage.local.set({[K.panelVisible]:!document.hidden}));
chrome.tabs.onActivated.addListener(()=>loadCurrentNote(false).catch(console.error));
chrome.tabs.onUpdated.addListener((_tabId,info)=>{ if(info.status==='complete') loadCurrentNote(false).catch(console.error); });
function wireButtons(){ document.getElementById('scopeGlobal').addEventListener('click',async()=>{ await setScopeMode('global'); await loadCurrentNote(); }); document.getElementById('scopePage').addEventListener('click',async()=>{ await setScopeMode('page'); await loadCurrentNote(); }); document.getElementById('scopeExternal').addEventListener('click',async()=>{ const state=await getPageState(); if(!(state.ctx.speechMiner&&state.ctx.externalId)) return setStatus('Trang này chưa có externalId để lưu theo interaction.','err'); await setScopeMode('externalId'); await loadCurrentNote(); }); document.getElementById('btnSingle').addEventListener('click',()=>openQuickNote('single').catch(console.error)); document.getElementById('btnRange').addEventListener('click',()=>openQuickNote('range').catch(console.error)); document.getElementById('btnFree').addEventListener('click',()=>openQuickNote('free').catch(console.error)); document.getElementById('btnToggleLabels').addEventListener('click',()=>setShowLabels(!showMarkerLabels).catch(console.error)); document.getElementById('btnSave').addEventListener('click',()=>saveCurrentNote(true,true).catch(console.error)); document.getElementById('btnClear').addEventListener('click',clearCurrentNote); document.getElementById('btnSettings').addEventListener('click',async()=>{ settingsBox.classList.toggle('open'); await renderSettings(); }); document.getElementById('btnSourceActive').addEventListener('click',()=>setActiveTabAsSource().catch(console.error)); document.getElementById('btnSourceManual').addEventListener('click',()=>chooseSourceManual().catch(console.error)); document.getElementById('btnSourceLock').addEventListener('click',()=>toggleSourceLock().catch(console.error)); document.getElementById('btnPluginToggle').addEventListener('click',()=>togglePlugin().catch(console.error)); document.getElementById('captureSingle').addEventListener('click',()=>{ captureMode='single'; setStatus('Nhấn tổ hợp phím mới cho Hotkey đơn','warn'); }); document.getElementById('captureRange').addEventListener('click',()=>{ captureMode='range'; setStatus('Nhấn tổ hợp phím mới cho Hotkey range','warn'); }); document.getElementById('clearSingle').addEventListener('click',async()=>{ const s=await getSettings(); s.singleHotkey.enabled=false; await saveSettings(s); await renderSettings(); setStatus('Đã tắt Hotkey đơn','ok'); }); document.getElementById('clearRange').addEventListener('click',async()=>{ const s=await getSettings(); s.rangeHotkey.enabled=false; await saveSettings(s); await renderSettings(); setStatus('Đã tắt Hotkey range','ok'); }); }
ensureActionIcons(); wireButtons(); (async()=>{ await set({[K.panelVisible]:true}); await loadShowLabels(); updatePluginUI(); await renderSettings(); await loadCurrentNote(); rememberNoteSelection(); })();
